data:
  pt_1: '..\resources\df_final_web_data_pt_1.txt'
  pt_2: '..\resources\df_final_web_data_pt_2.txt'
  demo_final: '..\resources\df_final_demo.txt'
  exp_client: '..\resources\df_final_experiment_clients.txt'